#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
# SCREENSHOT="scrot -z $PICTURE"
SCREENSHOT="import -screen -window root ${PICTURE}"

BLUR="9x8"

$SCREENSHOT
convert $PICTURE -blur $BLUR $PICTURE
i3lock -i $PICTURE
rm $PICTURE
